#{% set version = "3.6.1" %}
#{% set sha_value = "7ef271ae7cd10197ca96923b31ca8e45ccf434dc9824be994640bf15850487e4" %}
#NB get sha256 with: curl -sL <URL> | openssl sha256

package:
  name: mcstas
#  version: {{ version }}
  version: 3.9999

source:
#  url: https://github.com/mctools/ncrystal/archive/v{{ version }}.tar.gz
#  sha256: {{ sha_value }}
  path: ../../
  folder: src

build:
  number: 0
  noarch: generic
#  skip: true  # [win]

requirements:
  run:
    - mcstas-core
    - mcstas-data
    - mcstas-mcgui
    - mcstas-vis
    # mcstas-mpi ??
    - ncrystal # [unix]
    - mcpl     # [unix]

outputs:
  - name: mcstas-core
    #FIXME where then? noarch: python
    script: install-files-core.py
    requirements:
      build:
        - python
        - cmake
        - make  # [not win]
        - {{ compiler('c') }}
      run:
        - python
        - {{ compiler('c') }}
        - bash # for mcrun, and maybe others
        - pyaml # for mcrun
        - ply # for traces from mcrun

  - name: mcstas-data
    noarch: generic
    script: install-files-data.py

  - name: mcstas-mcgui
    noarch: generic
    requirements:
      run:
        - mcstas-core
        - pyqt
        - qscintilla2

  - name: mcstas-vis
    noarch: generic
    requirements:
      run:
        - mcstas-core
        - matplotlib
        - numpy
        - tornado
        - scipy
        - pillow
        - pyqtgraph
        - pyqt

  #FIXME: needs more work on mcstas-mpi:
  - name: mcstas-mpi
    noarch: generic
    requirements:
      run:
        - mcstas-core
       #NB: https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-builds
        - __win   # [win]
        - __unix  # [unix]
        - openmpi # [unix]

  - name: mcstas-all
    noarch: generic
    requirements:
      run:
        - mcstas-core
        - mcstas-data
        - mcstas-gui
        - mcstas-vis
        - mcstas-mpi
        - gsl
        - nomkl
        - nexusformat
        - nexpy
        - hdf5
#        - cadquery

test:
#FIXME:
#  requires:
#    - mcpl
#  imports:
#    - mcstas.cfg #does not exist yet
  files:
    - test_mcstas_cmd.x
  source_files:
    #Taking BNL_H8.instr from src rather than
    #$CONDA_PREFIX/share/mcstas/examples, since we might want to not install
    #examples along with mcstas/mcrun.
    #FIXME: this is for mcstas-core specific test?
    - src/mcstas-comps/examples/BNL_H8.instr
  commands:
    - test -f "${PREFIX}/bin/mcstas"
    - ./test_mcstas_cmd.x
about:
  home: https://mcstas.org/
  summary: McStas is a general tool for simulating neutron scattering instruments and experiments.
  description: |
    McStas is a general tool for simulating neutron scattering instruments and
    experiments.
  license: GPL3
  license_family: GPL3
  license_file: src/COPYING
  doc_url: https://mcstas.org/
  dev_url: https://github.com/McStasMcXtrace/McCode

extra:
  recipe-maintainers:
    - willend
    - tkittel


#NB other deps: openmpi gsl matplotlib numpy tornado scipy pillow pyqtgraph pyqt nomkl qscintilla2 nexusformat nexpy hdf5

#mcstas
#mcstas openmpi
#mcstas-mpi
