#{% set version = "3.6.1" %}
#{% set sha_value = "7ef271ae7cd10197ca96923b31ca8e45ccf434dc9824be994640bf15850487e4" %}
#NB get sha256 with: curl -sL <URL> | openssl sha256

package:
  name: mcstas-core
#  version: {{ version }}
  version: 3.9999

source:
#  url: https://github.com/mctools/ncrystal/archive/v{{ version }}.tar.gz
#  sha256: {{ sha_value }}
  path: ../../
  folder: src

build:
  number: 0
  skip: true  # [win]
#  skip: true  # [py<36]

requirements:
  build:
    - cmake
    - make  # [not win]
    - {{ compiler('c') }}
  host:
    #NB: host should not be empty:
    - bash
  run:
    - python
    - {{ compiler('c') }}
    - bash
    - pyaml # for mcrun
    - ply # for traces fra mcrun

test:
#  requires:
#    - ncrystal
#    - mcpl
#  imports:
#    - mcstas.cfg #does not exist yet
  files:
    - test_mcstas_cmd.x
  source_files:
    #Taking BNL_H8.instr from src rather than
    #$CONDA_PREFIX/share/mcstas/examples, since we might want to not install
    #examples along with mcstas/mcrun.
    - src/mcstas-comps/examples/BNL_H8.instr
  commands:
    - test -f "${PREFIX}/bin/mcstas"
    - ./test_mcstas_cmd.x
about:
  home: https://mcstas.org/
  summary: McStas is a general tool for simulating neutron scattering instruments and experiments.
  description: |
    McStas is a general tool for simulating neutron scattering instruments and
    experiments.
  license: GPL3
  license_family: GPL3
  license_file: src/COPYING
  doc_url: https://mcstas.org/
  dev_url: https://github.com/McStasMcXtrace/McCode

extra:
  recipe-maintainers:
    - willend
    - tkittel
